### PR TITLE
feat: Allow using a topic from outside of the module

### PR DESCRIPTION
**Pull request by atorrescogollo**
Based on the [AWS provider docs](https://registry.terraform.io/providers/hashicorp/aws/5.31.0/docs/resources/s3_bucket_notification):
>S3 Buckets only support a single notification configuration. Declaring multiple aws_s3_bucket_notification resources to the same S3 Bucket will cause a perpetual difference in configuration.

With the current code, since it creates both the topic and the notification, you can't listen to CloudTrail events through the bucket from another topic/sqs/lambda/... that is not the clickops-notifier.

With the new code, the module allows you to subscribe to a topic that is already created if you set the `cloudtrail_bucket_notifications_sns_arn` variable. That way, it doesn't block others from listening to S3 events.

### CODE REVIEW

**Comment by atorrescogollo** [comment]
@baolsen I just updated to PR to pass pre-commit checks

**Comment by baolsen** [comment]
@atorrescogollo thanks for the contribution.
I'll get the tests to run, it is an unrelated issue

**Comment by baolsen** [comment]
@atorrescogollo I think it should work now, please push an empty commit.

`git commit --allow-empty -m "empty"`

**Comment by baolsen** [comment]
@atorrescogollo I'm not yet certain why the test action isn't working.

On another PR I merged a few min it ran through fine o_O

I've updated the aws-actions/configure-aws-credentials to v4, seems there were some related fixes a few months ago.

Please merge one more time [Merge branch 'cloudandthings:main' into main]

**Comment by atorrescogollo** [comment]
Hi @baolsen , I already merged from upstream main. Can you approve it to run the tests again?

**Comment by baolsen** [comment]
Thanks @atorrescogollo for your patience.

I'm not sure why it's still giving an issue. 
Definitely your changes have nothing to do with it.

I'm going to merge this and then I'll create a dummy PR to run the tests.

Once that's done I'll cut a release.

**Comment by baolsen** [comment]
@atorrescogollo 

The tests ran through fine. Thanks again for the contribution!
Released with v5.1.0

**Pull request merged**
